### PR TITLE
nexus integration

### PR DESCRIPTION
**Pull request by arnaudon**
WIP branch

### CODE REVIEW

**Comment by arnaudon** [comment]
- The dataset_df has exists=True, which fails if I put a nexus url.
- for each task, it tries to dl from nexus the same dataset, we need to think of a way to solve that (currently, I just copied the output of Collect to a dataset.csv file as if it was given as usual.

**Comment by adrien-berchet** [comment]
> * The dataset_df has exists=True, which fails if I put a nexus url.
I just had a quick look but if you want to use nexus, shouldn't you put the URL into the `nexus_dataset_url` parameter instead of  `dataset_df`?

>     * for each task, it tries to dl from nexus the same dataset, we need to think of a way to solve that (currently, I just copied the output of Collect to a dataset.csv file as if it was given as usual.
We could add a cache mechanism to prevent each task from reloading the DF. I can try to add this feature once the rest of this PR is ready.

**Comment by arnaudon** [comment]
Yes, I added this new nexus_daataset_url for that purpose. In gitlab version, I was using dataset_df parameter for the URL, and it was working. 

Good idea for the cache!

**Comment by adrien-berchet** [comment]
Ah yes, I think I see the issue for the `dataset_df`. I guess we could create a new parameter class for which the `normalize` method would be something like:
```python
    def normalize(self, x):
        """Normalize the given value to a :class:`pathlib.Path` object or a Nexus path."""
        if x 'IS LIKE A NEXUS PATH':
            return NEXUS_NORMALIZATION(x)
        else:
            return super().normalize(x)
```

**Pull request closed without merging**
