### PR TITLE
Fix SSL certificate in example

### PR DESCRIPTION
**Pull request by arnaudon**

### CODE REVIEW

**Comment by adrien-berchet** [comment]
Ah cool, thanks!

**Review by adrien-berchet — APPROVED** [review]

**Comment by arnaudon** [comment]
but I didn't do it haha

**Comment by arnaudon** [comment]
I think it's an issue that can be solved in morphapi

**Comment by arnaudon** [comment]
this should do it I believe: https://github.com/brainglobe/morphapi/pull/17

**Pull request merged**
