### PR TITLE
Release: 0.12.0

### PR DESCRIPTION
**Pull request by arnaudon**

### CODE REVIEW

**Comment by adrien-berchet** [comment]
Wait, I just remembered I still have a minor improvement to do in another PR. It won't be long.

**Comment by adrien-berchet** [comment]
Ah also needs #160 :smile:

**Review by adrien-berchet — APPROVED** [review]

**Comment by arnaudon** [comment]
haha, all good?

**Comment by adrien-berchet** [comment]
This time it's good for me :)

**Comment by arnaudon** [comment]
ok, I'll still wait for the CI, in case you messed up ;P

**Comment by adrien-berchet** [comment]
> ok, I'll still wait for the CI, in case you messed up ;P

CI passed :stuck_out_tongue_winking_eye:

**Pull request merged**
